name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      actions: write

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.0
      - run: npm install

      - name: Build/release Electron app on Linux
        if: runner.os == 'Linux'
        run: |
          npx electron-builder --linux appimage tar.gz  # Specify Linux targets to avoid .deb
        continue-on-error: true

      - name: Build/release Electron app on Windows
        if: runner.os == 'Windows'
        run: |
          npx electron-builder --win nsis zip  # Specify Windows targets
        continue-on-error: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-builds-${{ runner.os }}
          path: dist/**/* # Upload all files from the dist directory
